#!/usr/bin/perl -w

$char = '*';
$fill = ' ';

if($ARGC < 1) {
  print "Usage: $0 [number] [options]\n",
        "Options:\n",
        "\t-f, --fill = fill triangle with set character\n",
        "\t-c, --character = set character (default *)\n";
  exit 0;
}

for(@ARGV) {
  chomp $_;
  if($charopt) {
    if(/^.$/) {
      $char=$_;
      if($fill ne ' ') {
        $fill = $char;
      }
    } else {
      print STDERR "error: charcter can only be one character long\n";
      exit 1;
    }
    $charopt=0;
  } elsif(/^-c/ or /^--character/) {
    $charopt=1;
  } elsif(/^-f/ or /^--fill/) {
    $fill = $char;
  } else {
    $size = $_;
  }
}

if($size =~ /\D+/) {
  print "Enter a number!\n";
  exit 0;
}
elsif(!($size % 2)) {
  $size--;
  print "your number has been demoted to $size because it is an even number.\n";
}
for($i=0; ($size-3)/2+1 >= $i; $i++) {
  for($j=0; ($size-3)/2-$i >= $j; $j++) {
    print " ";
  }
if($i==0) {
  print "$char\n";
}
else {
  if($i == ($size-3)/2+1) {
    $fill = $char;
  }
  print $char;
  for($j=0; 2*$i-2 >= $j; $j++) {
    print $fill;
  }
  print "$char\n";
}
}
