#!/usr/bin/perl

$char = '*';
$fill = ' ';
my $triangle_line;
my $down;
my @triangle;
$down=1;

sub usage {
  print "Usage: $0 [number] [options]\n",
        "Options:\n",
        "\t-f, --fill = fill triangle with set character\n",
        "\t-c [character], --character [character] = set character (default *)\n",
        "\t-d, --down = makes triangle point down\n";
}

for(@ARGV) {
  chomp $_;
  if($charopt) {
    if(/^.$/) {
      $char=$_;
      if($fill ne ' ') {
        $fill = $char;
      }
    } elsif(/^rand(om)?$/) {
      $char = chr(rand(93)+33);
      if($fill ne ' ') {
        $fill = $char;
      }
    } else {
      print STDERR "error: charcter can only be one character long\n";
      exit 1;
    }
    $charopt=0;
  } elsif(/^-c$|^--character$/) {
    $charopt=1;
  } elsif(/^-f$|^--fill$/) {
    $fill = $char;
  } elsif(/^-d$|^--down$/) {
    $down=1;
  } else {
    $size = $_;
  }
}

if($size == undef) {
  &usage;
  exit 0;
}

if($size =~ /\D+/) {
  print "Enter a number!\n";
  exit 0;
}
elsif(!($size % 2)) {
  $size--;
  print "your number has been demoted to $size because it is an even number.\n";
}
for($i=0; ($size-3)/2+1 >= $i; $i++) {
  $triangle_line=undef;
  for($j=0; ($size-3)/2-$i >= $j; $j++) {
    $triangle_line .= " ";
  }
  if($i==0) {
    $triangle_line .= "$char";
  }
  else {
    if($i == ($size-3)/2+1) {
      $fill = $char;
    }
    $triangle_line .= $char;
    for($j=0; 2*$i-2 >= $j; $j++) {
      $triangle_line .= $fill;
    }
    $triangle_line .= "$char";
  }
  push @triangle, $triangle_line;
}

$, = "\n";
if($down) {
  print reverse @triangle;
}
else {
  print @triangle;
}
print "\n";
